AWSTemplateFormatVersion: '2010-09-09'
Description: "Project Name: Stack Description."

Metadata:
  TemplateName: root-stack.yaml
  TemplateType: Root Stack Template for <Service Names>
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName:  Project Name
  Modification History:
    - 1.0.0 - Jan 31, 2025 -- Initial Version
  StepsToTest: Manually verify the Stack.
  StepsToCleanup: Stack delete command
  AWS::CloudFormation::Interface:
    ParameterGroups:
      ################################## Project Name and Environment ##############################
      - Label:
          default: 'Project Name and Environment:'
        Parameters:
          - ProjectName
          - Environment
      ################################## GitHub Attributes #########################################
      - Label:
          default: 'GitHub Attributes:'
        Parameters:
          - GitHubRef
          - GitHubURL
          - GitHubWFRunNumber
          - GitHubSHA
          - GitHubRepository
          - CiBuild
      ################################## Code Repository ###########################################
      - Label:
          default: 'Code Repository:'
        Parameters:
          - CodeRepositoryS3Bucket
      ################################## KMS #######################################################
      - Label:
          default: "KMS Key:"
        Parameters:
          # - KmsMasterKeyAlias
          - KmsMasterKeyArn
      ################################## VPC Stack #################################################
      - Label:
          default: "VPC Stack Configuration:"
        Parameters:
          - VpcStackName
      ################################## S3 Bucket #################################################
      - Label:
          default: "S3 Bucket Configuration:"
        Parameters:
          - S3BucketBaseName
          - S3BucketBlockPublicAcls
          - S3BucketBlockPublicPolicy
          - S3BucketIgnorePublicAcls
          - S3BucketRestrictPublicBuckets
          - BucketVersioningEnabled
      ################################## Lifecycle Configuration ###################################
      - Label:
          default: "S3 Bucket Lifecycle Configuration:"
        Parameters:
          - S3LifecycleConfigurationEnabled
          - TransitionPrefix
          - StandardIATransitionEnabled
          - TransitionToIADays
          - IntelligentTieringEnabled
          - TransitionToITDays
          - OneZoneIATransitionEnabled
          - TransitionToOZIADays
          - GlacierIRTransitionEnabled
          - TransitionToGlacierIRDays
          - GlacierTransitionEnabled
          - TransitionToGlacierDays
          - DeepArchiveTransitionEnabled
          - TransitionToDeepArchiveDays
          - EnableExpiration
          - ExpirationDays
  ParameterLabels:
    ################################## Project Name and Environment ##############################
    ProjectName:
      default: "Name of the Project."
    Environment:
      default: "Name of the Deployment Environment."

    ################################## GitHub Attributes #########################################
    GitHubRef:
      default: "GitHub Reference Branch or Tag."
    GitHubURL:
      default: "URL of the GitHub Repository."
    GitHubWFRunNumber:
      default: "GitHub Workflow Execution Run Number."
    GitHubSHA:
      default: "GitHub Commit SHA."
    GitHubRepository:
      default: "Name of the GitHub Repository."
    CiBuild:
      default: "CI Build Identifier."

    ################################## Code Repository ###########################################
    CodeRepositoryS3Bucket:
      default: "S3 Bucket for Nested Templates."

    ################################## KMS #######################################################
    KmsMasterKeyArn:
      default: "KMS Master Key ARN."

    ################################## VPC Stack #################################################
    VpcStackName:
      default: "Name of the VPC Stack."

    ################################## S3 Bucket #################################################
    S3BucketBaseName:
      default: "S3 Bucket Base Name."
    S3BucketBlockPublicAcls:
      default: "Block Public ACLs."
    S3BucketBlockPublicPolicy:
      default: "Block Public Policy."
    S3BucketIgnorePublicAcls:
      default: "Ignore Public ACLs."
    S3BucketRestrictPublicBuckets:
      default: "Restrict Public Buckets."
    BucketVersioningEnabled:
      default: "Enable Bucket Versioning."

    ################################## Lifecycle Configuration ###################################
    S3LifecycleConfigurationEnabled:
      default: "Enable Lifecycle Configuration."
    TransitionPrefix:
      default: "Lifecycle Transition Prefix."
    StandardIATransitionEnabled:
      default: "Enable Standard-IA Transition."
    TransitionToIADays:
      default: "Days Before Standard-IA Transition."
    IntelligentTieringEnabled:
      default: "Enable Intelligent Tiering Transition."
    TransitionToITDays:
      default: "Days Before Intelligent Tiering Transition."
    OneZoneIATransitionEnabled:
      default: "Enable One Zone-IA Transition."
    TransitionToOZIADays:
      default: "Days Before One Zone-IA Transition."
    GlacierIRTransitionEnabled:
      default: "Enable Glacier Instant Retrieval Transition."
    TransitionToGlacierIRDays:
      default: "Days Before Glacier Instant Retrieval Transition."
    GlacierTransitionEnabled:
      default: "Enable Glacier Transition."
    TransitionToGlacierDays:
      default: "Days Before Glacier Transition."
    DeepArchiveTransitionEnabled:
      default: "Enable Deep Archive Transition."
    TransitionToDeepArchiveDays:
      default: "Days Before Deep Archive Transition."
    EnableExpiration:
      default: "Enable Object Expiration."
    ExpirationDays:
      default: "Days Before Object Expiration."

Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: gh-cfn-templ
    Description: The Project name to be used as a resource tag value.
    Type: String
    MinLength: "5"
    MaxLength: "30"
    AllowedPattern: ^[a-z0-9-]+$
    ConstraintDescription: The length should be between 5 and 30, must contain only
      lowercase alphabets, numbers, or dashes.

  Environment:
    Default: devl
    Description: The Environment name to be used as a resource tag value.
    Type: String
    AllowedValues:
      - devl
      - test
      - prod
    ConstraintDescription: The Environment must be devl / test or prod
  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: GitHub Ref name to be used as a resource tag value.
    Type: String
    AllowedPattern: ^[a-zA-Z0-9/_-]+$
    ConstraintDescription: The GitHub Ref Name can only contain alphanumeric
      characters, slashes, underscores, and hyphens.

  GitHubURL:
    Default: https://github.com/subhamay-bhattacharyya/CloudFormation.Template
    Description: GitHub URL to be used as a resource tag value.
    Type: String
    AllowedPattern: ^https://github.com/[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+/?$
    ConstraintDescription: The GitHub URL must start with 'https://github.com/' and
      can only contain alphanumeric characters, dots, underscores, and hyphens.

  GitHubWFRunNumber:
    Default: "1"
    Description: The Workflow run number to be used as a resource tag value.
    Type: Number

  GitHubSHA:
    Default: d3b07384d113edec49eaa6238ad5ff00f6fb3796
    Description: The sha value of the last commit to be used as a resource tag value.
    Type: String
    AllowedPattern: ^[a-fA-F0-9]{40}$
    ConstraintDescription: The SHA value must be a 40-character hexadecimal string.

  GitHubRepository:
    Default: 0123-cloudformation-template
    Description: The GitHub Repository name to be used as a resource tag value.
    Type: String
    MinLength: "10"
    MaxLength: "30"
    AllowedPattern: ^\d{4}-[a-z]+(-[a-z]+)*$
    ConstraintDescription: The repository length should be between 10 and 30, must
      contain only lowercase letters, numbers, dashes, dots, and should start
      with four digit zero padded number.

  CiBuild:
    Default: ''
    Description: Ci Build of the feature branch to be appended to a resource name.
    Type: String
  ###################################### Code Repository ###########################################
  CodeRepositoryS3Bucket:
    Default: subhamay-aws-cfn-nested-stack-templates-us-east-1
    Description: S3 Bucket for the nested stack templates.
    Type: String
    AllowedPattern: ^[a-z0-9.-]{3,63}$
    ConstraintDescription: The S3 bucket name must be between 3 and 63 characters
      long, and can only contain lowercase letters, numbers, dots, and hyphens.

  ###################################### KMS #######################################################
  # KmsMasterKeyAlias:
  #   Default: "SB-KMS"
  #   Description: "The KMS master key alias to be used for server-side encryption."
  #   Type: String
  #   MinLength: "5"
  #   MaxLength: "20"
  #   AllowedPattern: "^[a-z0-9-]+$"
  #   ConstraintDescription: "The length of the KMS Key Alias should be between 5 and 20 and can only contain lowercase alphanumeric characters and dashes."

  KmsMasterKeyArn:
    Default: "arn:aws:kms:us-east-1:637423502513:key/494509e4-3bc5-44b8-9c4d-12449900d395"
    Description: "The KMS master key ARN to be used for server-side encryption."
    Type: String
    AllowedPattern: "^$|^arn:aws:kms:[a-z0-9-]+:[0-9]{12}:key/[a-zA-Z0-9-]+$"
    ConstraintDescription: "The ARN must be a valid KMS key ARN."
  ###################################### VPC Stack #################################################
  VpcStackName:
    Default: private-vpc-root-stack
    Description: The name of the VPC stack.
    Type: String
    AllowedPattern: ^[a-zA-Z0-9-]+$
    ConstraintDescription: The stack name can only contain alphanumeric characters and hyphens.
    MinLength: 3
    MaxLength: 128

  ###################################### S3 Bucket #################################################
  S3BucketBaseName:
    Default: cfn-templates
    Description: "The base name for the S3 bucket used for source data. The region will be added as a suffix by the template."
    Type: String
    MinLength: "3"
    MaxLength: "20"
    AllowedPattern: "^[a-z0-9.-]{3,20}$"
    ConstraintDescription: "The S3 bucket name must be 3-63 characters long and can only include lowercase letters, numbers, dots, and hyphens."

  S3BucketBlockPublicAcls:
    Default: "true"
    Description: "Indicates whether to block public ACLs for the S3 bucket."
    Type: String
    AllowedValues: ["true", "false"]

  S3BucketBlockPublicPolicy:
    Default: "true"
    Description: "Indicates whether to block public policies for the S3 bucket."
    Type: String
    AllowedValues: ["true", "false"]

  S3BucketIgnorePublicAcls:
    Default: "true"
    Description: "Indicates whether to ignore public ACLs for the S3 bucket."
    Type: String
    AllowedValues: ["true", "false"]

  S3BucketRestrictPublicBuckets:
    Default: "true"
    Description: "Indicates whether to restrict public access to the S3 bucket."
    Type: String
    AllowedValues: ["true", "false"]

  BucketVersioningEnabled:
    Default: "false"
    Description: "Specifies whether versioning is enabled for the S3 bucket."
    Type: String
    AllowedValues: ["true", "false"]

  ##################################### Lifecycle Configuration ###################################
  S3LifecycleConfigurationEnabled:
    Default: "false"
    Description: "Indicates whether lifecycle configuration is enabled for the S3 bucket."
    Type: String
    AllowedValues: ["true", "false"]

  TransitionPrefix:
    Default: "data/"
    Description: "Specifies the prefix for objects to apply lifecycle transitions."
    Type: String

  StandardIATransitionEnabled:
    Default: "false"
    Description: "Specifies whether objects are transitioned to Standard-IA storage."
    Type: String
    AllowedValues: ["true", "false"]

  TransitionToIADays:
    Default: "30"
    Description: "The number of days before objects transition to Standard-IA storage."
    Type: Number
    MinValue: "30"
    MaxValue: "185"

  IntelligentTieringEnabled:
    Default: "false"
    Description: "Specifies whether objects are transitioned to Intelligent Tiering storage."
    Type: String
    AllowedValues: ["true", "false"]

  TransitionToITDays:
    Default: "60"
    Description: "The number of days before objects transition to Intelligent Tiering storage."
    Type: Number
    MinValue: "60"
    MaxValue: "365"

  OneZoneIATransitionEnabled:
    Default: "false"
    Description: "Specifies whether objects are transitioned to One Zone-IA storage."
    Type: String
    AllowedValues: ["true", "false"]

  TransitionToOZIADays:
    Default: "90"
    Description: "The number of days before objects transition to One Zone-IA storage."
    Type: Number
    MinValue: "90"
    MaxValue: "365"

  GlacierIRTransitionEnabled:
    Default: "false"
    Description: "Specifies whether objects are transitioned to Glacier Instant Retrieval storage."
    Type: String
    AllowedValues: ["true", "false"]

  TransitionToGlacierIRDays:
    Default: "120"
    Description: "The number of days before objects transition to Glacier Instant Retrieval storage."
    Type: Number
    MinValue: "120"
    MaxValue: "365"

  GlacierTransitionEnabled:
    Default: "false"
    Description: "Specifies whether objects are transitioned to Glacier storage."
    Type: String
    AllowedValues: ["true", "false"]

  TransitionToGlacierDays:
    Default: "60"
    Description: "The number of days before objects transition to Glacier storage."
    Type: Number
    MinValue: "60"
    MaxValue: "500"

  DeepArchiveTransitionEnabled:
    Default: "false"
    Description: "Specifies whether objects are transitioned to Deep Archive storage."
    Type: String
    AllowedValues: ["true", "false"]

  TransitionToDeepArchiveDays:
    Default: "365"
    Description: "The number of days before objects transition to Deep Archive storage."
    Type: Number
    MinValue: "365"
    MaxValue: "500"

  EnableExpiration:
    Default: "false"
    Description: "Indicates whether expiration is enabled for objects in the S3 bucket."
    Type: String
    AllowedValues: ["true", "false"]

  ExpirationDays:
    Default: "90"
    Description: "The number of days before objects in the S3 bucket are expired."
    Type: Number
    MinValue: "30"
    MaxValue: "365"
Resources:
  ###################################### S3 Bucket #################################################
  S3Bucket:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Type: AWS::CloudFormation::Stack
    # DependsOn:
    #   - LambdaRole
    Properties:
      TemplateURL: !Sub "https://${CodeRepositoryS3Bucket}.s3.amazonaws.com/s3/s3-bucket.yaml"
      Parameters:
        S3BucketBaseName: !Ref S3BucketBaseName
        S3BucketBlockPublicAcls: !Ref S3BucketBlockPublicAcls
        S3BucketBlockPublicPolicy: !Ref S3BucketBlockPublicPolicy
        S3BucketIgnorePublicAcls: !Ref S3BucketIgnorePublicAcls
        S3BucketRestrictPublicBuckets: !Ref S3BucketRestrictPublicBuckets
        BucketVersioningEnabled: !Ref BucketVersioningEnabled
        KmsMasterKeyArn: !Ref KmsMasterKeyArn
        S3VpcEndpointId: !ImportValue
          Fn::Sub: "${VpcStackName}-S3GatewayVpceId"
        # IAMRoleBaseName: "lambda-role"
        WhitelistedUserId: AIDAZI2LGYSY7WDKOVKYW
        WhitelistedRoleId: AROAZI2LGYSYVKL4XJGIN
        S3LifecycleConfigurationEnabled: !Ref S3LifecycleConfigurationEnabled
        TransitionPrefix: !Ref TransitionPrefix
        StandardIATransitionEnabled: !Ref StandardIATransitionEnabled
        TransitionToIADays: !Ref TransitionToIADays
        IntelligentTieringEnabled: !Ref IntelligentTieringEnabled
        TransitionToITDays: !Ref TransitionToITDays
        OneZoneIATransitionEnabled: !Ref OneZoneIATransitionEnabled
        TransitionToOZIADays: !Ref TransitionToOZIADays
        GlacierIRTransitionEnabled: !Ref GlacierIRTransitionEnabled
        TransitionToGlacierIRDays: !Ref TransitionToGlacierIRDays
        GlacierTransitionEnabled: !Ref GlacierTransitionEnabled
        TransitionToGlacierDays: !Ref TransitionToGlacierDays
        DeepArchiveTransitionEnabled: !Ref DeepArchiveTransitionEnabled
        TransitionToDeepArchiveDays: !Ref TransitionToDeepArchiveDays
        EnableExpiration: !Ref EnableExpiration
        ExpirationDays: !Ref ExpirationDays
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        GitHubRef: !Ref GitHubRef
        GitHubURL: !Ref GitHubURL
        GitHubWFRunNumber: !Ref GitHubWFRunNumber
        GitHubSHA: !Ref GitHubSHA
        GitHubRepository: !Ref GitHubRepository
        CiBuild: !Ref CiBuild
      TimeoutInMinutes: 30
Outputs:
  ###################################### S3 Bucket #################################################
  S3BucketArn:
    Description: Arn of the S3 bucket.
    Value: !GetAtt S3Bucket.Outputs.S3BucketArn
