name: Build and Test
run-name: CloudFormation Stack Build and Test by ${{ github.actor }} on ${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  build:
    name: "CloudFormation Build"
    runs-on: ubuntu-latest
    
    permissions:
      # contents: read
      # packages: read
      # To report GitHub Actions status checks
      # statuses: write
      # To use OIDC
      id-token: write
      
    steps:
      - name: Scan and Validate
        id: scan-validate
        uses: subhamay-bhattacharyya-gha/cfn-build-test-action-test@main
        with:
          aws-role-arn: arn:aws:iam::637423502513:role/subhamay-github-oidc-role
          aws-region: us-east-1
          template-dir: "cfn"
          template-file: "root-stack-template.yaml"
          iac-framework: "cloudformation"
          soft-fail: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
